### ISSUE TITLE
zs.TraceID.ToHex undefined (type model.TraceID has no field or method ToHex)

### ISSUE THREAD

**Issue by al3rez** [lileio/logr#2]
I was installing your generator and I got this error message which it seems it's kind of related to zipkin-go-opentracing interface. FYI https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/142

**Comment by arbarlow** [comment]
Hi there, are you using go modules?

**Comment by al3rez** [comment]
Yeah

**Comment by arbarlow** [comment]
This should be resolved now! Let me know if you're still having issues
